### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by ninjaparade** [blogsend/wordpress-plugin#1]
FIX ASAP!

**Comment by mtimofiiv** [comment]
<img src="https://images.says.com/uploads/story_source/source_image/656219/fb96.gif" width="100%">

**Comment by ninjaparade** [comment]
![i love changes](https://user-images.githubusercontent.com/228899/51121906-69118080-17cd-11e9-9829-aa0a56a0662e.gif)

**Comment by mtimofiiv** [comment]
<img src="https://user-images.githubusercontent.com/428948/51582807-5cdd9f80-1f00-11e9-8f7f-e72bca484ca4.gif" width="100%">

Enjoy this woman caressing a digital taco
